//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycleTimeRecord.TransferServiceAMES {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransferServiceAMES.TransferServiceSoap")]
    public interface TransferServiceSoap {
        
        // CODEGEN: 參數 'itemType' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CycleTimeRecord.TransferServiceAMES.TxItemResponse TxItem(CycleTimeRecord.TransferServiceAMES.TxItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxItem", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxItemResponse> TxItemAsync(CycleTimeRecord.TransferServiceAMES.TxItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxProductType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TxProductType(string typeNo, string typeName, string typeDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxProductType", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TxProductTypeAsync(string typeNo, string typeName, string typeDesc);
        
        // CODEGEN: 參數 'productTypeId' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CycleTimeRecord.TransferServiceAMES.TxModelResponse TxModel(CycleTimeRecord.TransferServiceAMES.TxModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxModel", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxModelResponse> TxModelAsync(CycleTimeRecord.TransferServiceAMES.TxModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxFlow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TxFlow(string flowName, string flowDesc, string unitNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxFlow", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TxFlowAsync(string flowName, string flowDesc, string unitNo);
        
        // CODEGEN: 參數 'planQty' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxWorkOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoResponse TxWorkOrderInfo(CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxWorkOrderInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoResponse> TxWorkOrderInfoAsync(CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoRequest request);
        
        // CODEGEN: 參數 'planQty' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxWorkOrderInsertAndStart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartResponse TxWorkOrderInsertAndStart(CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxWorkOrderInsertAndStart", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartResponse> TxWorkOrderInsertAndStartAsync(CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PassStation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PassStation(string barcodeNo, int lineId, string unitNo, int stationId, int woId, int flowId, System.DateTime collectDate, string ruleStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PassStation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PassStationAsync(string barcodeNo, int lineId, string unitNo, int stationId, int woId, int flowId, System.DateTime collectDate, string ruleStatus);
        
        // CODEGEN: 參數 'POWER_ID' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxWorkManpower", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CycleTimeRecord.TransferServiceAMES.TxWorkManpowerResponse TxWorkManpower(CycleTimeRecord.TransferServiceAMES.TxWorkManpowerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxWorkManpower", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkManpowerResponse> TxWorkManpowerAsync(CycleTimeRecord.TransferServiceAMES.TxWorkManpowerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RvSensorByIp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RvSensorByIp(string deviceIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RvSensorByIp", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RvSensorByIpAsync(string deviceIp);
        
        // CODEGEN: 參數 'sensorId' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxSensorLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CycleTimeRecord.TransferServiceAMES.TxSensorLogResponse TxSensorLog(CycleTimeRecord.TransferServiceAMES.TxSensorLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxSensorLog", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxSensorLogResponse> TxSensorLogAsync(CycleTimeRecord.TransferServiceAMES.TxSensorLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RvWoYieldData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RvWoYieldData(string woNo, string engSr, string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RvWoYieldData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RvWoYieldDataAsync(string woNo, string engSr, string startDate, string endDate);
        
        // CODEGEN: 參數 'stdID' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxStandardTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CycleTimeRecord.TransferServiceAMES.TxStandardTimeResponse TxStandardTime(CycleTimeRecord.TransferServiceAMES.TxStandardTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxStandardTime", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxStandardTimeResponse> TxStandardTimeAsync(CycleTimeRecord.TransferServiceAMES.TxStandardTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxItem", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string itemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string itemName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string itemDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> itemType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string uniqueFlag;
        
        public TxItemRequest() {
        }
        
        public TxItemRequest(string itemNo, string itemName, string itemDesc, System.Nullable<int> itemType, string uniqueFlag) {
            this.itemNo = itemNo;
            this.itemName = itemName;
            this.itemDesc = itemDesc;
            this.itemType = itemType;
            this.uniqueFlag = uniqueFlag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxItemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TxItemResult;
        
        public TxItemResponse() {
        }
        
        public TxItemResponse(string TxItemResult) {
            this.TxItemResult = TxItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxModel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string modelNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string modelName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string modelSpec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string modelUnit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string modelDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string modelGroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> productTypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string modelType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> burnTime;
        
        public TxModelRequest() {
        }
        
        public TxModelRequest(string modelNo, string modelName, string modelSpec, string modelUnit, string modelDesc, string modelGroup, System.Nullable<int> productTypeId, string modelType, System.Nullable<int> burnTime) {
            this.modelNo = modelNo;
            this.modelName = modelName;
            this.modelSpec = modelSpec;
            this.modelUnit = modelUnit;
            this.modelDesc = modelDesc;
            this.modelGroup = modelGroup;
            this.productTypeId = productTypeId;
            this.modelType = modelType;
            this.burnTime = burnTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxModelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TxModelResult;
        
        public TxModelResponse() {
        }
        
        public TxModelResponse(string TxModelResult) {
            this.TxModelResult = TxModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxWorkOrderInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxWorkOrderInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string woNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> planQty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string unitNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> productTypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string modelNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> woType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string engSr;
        
        public TxWorkOrderInfoRequest() {
        }
        
        public TxWorkOrderInfoRequest(string woNo, System.Nullable<int> planQty, string unitNo, System.Nullable<int> productTypeId, string modelNo, System.Nullable<int> woType, string engSr) {
            this.woNo = woNo;
            this.planQty = planQty;
            this.unitNo = unitNo;
            this.productTypeId = productTypeId;
            this.modelNo = modelNo;
            this.woType = woType;
            this.engSr = engSr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxWorkOrderInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxWorkOrderInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TxWorkOrderInfoResult;
        
        public TxWorkOrderInfoResponse() {
        }
        
        public TxWorkOrderInfoResponse(string TxWorkOrderInfoResult) {
            this.TxWorkOrderInfoResult = TxWorkOrderInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxWorkOrderInsertAndStart", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxWorkOrderInsertAndStartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string woNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> planQty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string unitNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> productTypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string modelNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> woType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> lineId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> flowId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string engSr;
        
        public TxWorkOrderInsertAndStartRequest() {
        }
        
        public TxWorkOrderInsertAndStartRequest(string woNo, System.Nullable<int> planQty, string unitNo, System.Nullable<int> productTypeId, string modelNo, System.Nullable<int> woType, System.Nullable<int> lineId, System.Nullable<int> flowId, string engSr) {
            this.woNo = woNo;
            this.planQty = planQty;
            this.unitNo = unitNo;
            this.productTypeId = productTypeId;
            this.modelNo = modelNo;
            this.woType = woType;
            this.lineId = lineId;
            this.flowId = flowId;
            this.engSr = engSr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxWorkOrderInsertAndStartResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxWorkOrderInsertAndStartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TxWorkOrderInsertAndStartResult;
        
        public TxWorkOrderInsertAndStartResponse() {
        }
        
        public TxWorkOrderInsertAndStartResponse(string TxWorkOrderInsertAndStartResult) {
            this.TxWorkOrderInsertAndStartResult = TxWorkOrderInsertAndStartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxWorkManpower", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxWorkManpowerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> POWER_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string POWER_DATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string USER_NO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string USER_NAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string UNIT_NO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CLASS_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> OVER_H;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PREPAR_REST_H;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> FACT_REST_H;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> LEAVE_H;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public double FACT_WORK_H;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BREAK_TIME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string CLASS_NO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string WERKS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LINE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> STATION_ID;
        
        public TxWorkManpowerRequest() {
        }
        
        public TxWorkManpowerRequest(
                    System.Nullable<int> POWER_ID, 
                    string POWER_DATE, 
                    string USER_NO, 
                    string USER_NAME, 
                    string UNIT_NO, 
                    System.Nullable<int> CLASS_ID, 
                    System.Nullable<double> OVER_H, 
                    System.Nullable<double> PREPAR_REST_H, 
                    System.Nullable<double> FACT_REST_H, 
                    System.Nullable<double> LEAVE_H, 
                    double FACT_WORK_H, 
                    System.Nullable<int> BREAK_TIME, 
                    string CLASS_NO, 
                    string WERKS, 
                    System.Nullable<int> LINE_ID, 
                    System.Nullable<int> STATION_ID) {
            this.POWER_ID = POWER_ID;
            this.POWER_DATE = POWER_DATE;
            this.USER_NO = USER_NO;
            this.USER_NAME = USER_NAME;
            this.UNIT_NO = UNIT_NO;
            this.CLASS_ID = CLASS_ID;
            this.OVER_H = OVER_H;
            this.PREPAR_REST_H = PREPAR_REST_H;
            this.FACT_REST_H = FACT_REST_H;
            this.LEAVE_H = LEAVE_H;
            this.FACT_WORK_H = FACT_WORK_H;
            this.BREAK_TIME = BREAK_TIME;
            this.CLASS_NO = CLASS_NO;
            this.WERKS = WERKS;
            this.LINE_ID = LINE_ID;
            this.STATION_ID = STATION_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxWorkManpowerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxWorkManpowerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TxWorkManpowerResult;
        
        public TxWorkManpowerResponse() {
        }
        
        public TxWorkManpowerResponse(string TxWorkManpowerResult) {
            this.TxWorkManpowerResult = TxWorkManpowerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxSensorLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxSensorLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> sensorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> inputValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string logDatetime;
        
        public TxSensorLogRequest() {
        }
        
        public TxSensorLogRequest(System.Nullable<int> sensorId, System.Nullable<int> inputValue, string logDatetime) {
            this.sensorId = sensorId;
            this.inputValue = inputValue;
            this.logDatetime = logDatetime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxSensorLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxSensorLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TxSensorLogResult;
        
        public TxSensorLogResponse() {
        }
        
        public TxSensorLogResponse(string TxSensorLogResult) {
            this.TxSensorLogResult = TxSensorLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxStandardTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxStandardTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string txtype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> stdID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UNIT_NO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LINE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ITEM_NO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OP_CNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> FIRST_TIME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> TOTAL_CT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> CT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> MACHINE_CNT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string SIDE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> STATION_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string MEMO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string uID;
        
        public TxStandardTimeRequest() {
        }
        
        public TxStandardTimeRequest(string txtype, System.Nullable<int> stdID, string UNIT_NO, System.Nullable<int> LINE_ID, string ITEM_NO, System.Nullable<int> OP_CNT, System.Nullable<double> FIRST_TIME, System.Nullable<double> TOTAL_CT, System.Nullable<double> CT, System.Nullable<double> MACHINE_CNT, string SIDE, System.Nullable<int> STATION_ID, string MEMO, string uID) {
            this.txtype = txtype;
            this.stdID = stdID;
            this.UNIT_NO = UNIT_NO;
            this.LINE_ID = LINE_ID;
            this.ITEM_NO = ITEM_NO;
            this.OP_CNT = OP_CNT;
            this.FIRST_TIME = FIRST_TIME;
            this.TOTAL_CT = TOTAL_CT;
            this.CT = CT;
            this.MACHINE_CNT = MACHINE_CNT;
            this.SIDE = SIDE;
            this.STATION_ID = STATION_ID;
            this.MEMO = MEMO;
            this.uID = uID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TxStandardTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TxStandardTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TxStandardTimeResult;
        
        public TxStandardTimeResponse() {
        }
        
        public TxStandardTimeResponse(string TxStandardTimeResult) {
            this.TxStandardTimeResult = TxStandardTimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransferServiceSoapChannel : CycleTimeRecord.TransferServiceAMES.TransferServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransferServiceSoapClient : System.ServiceModel.ClientBase<CycleTimeRecord.TransferServiceAMES.TransferServiceSoap>, CycleTimeRecord.TransferServiceAMES.TransferServiceSoap {
        
        public TransferServiceSoapClient() {
        }
        
        public TransferServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransferServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.TransferServiceAMES.TxItemResponse CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxItem(CycleTimeRecord.TransferServiceAMES.TxItemRequest request) {
            return base.Channel.TxItem(request);
        }
        
        public string TxItem(string itemNo, string itemName, string itemDesc, System.Nullable<int> itemType, string uniqueFlag) {
            CycleTimeRecord.TransferServiceAMES.TxItemRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxItemRequest();
            inValue.itemNo = itemNo;
            inValue.itemName = itemName;
            inValue.itemDesc = itemDesc;
            inValue.itemType = itemType;
            inValue.uniqueFlag = uniqueFlag;
            CycleTimeRecord.TransferServiceAMES.TxItemResponse retVal = ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxItem(inValue);
            return retVal.TxItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxItemResponse> CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxItemAsync(CycleTimeRecord.TransferServiceAMES.TxItemRequest request) {
            return base.Channel.TxItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxItemResponse> TxItemAsync(string itemNo, string itemName, string itemDesc, System.Nullable<int> itemType, string uniqueFlag) {
            CycleTimeRecord.TransferServiceAMES.TxItemRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxItemRequest();
            inValue.itemNo = itemNo;
            inValue.itemName = itemName;
            inValue.itemDesc = itemDesc;
            inValue.itemType = itemType;
            inValue.uniqueFlag = uniqueFlag;
            return ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxItemAsync(inValue);
        }
        
        public string TxProductType(string typeNo, string typeName, string typeDesc) {
            return base.Channel.TxProductType(typeNo, typeName, typeDesc);
        }
        
        public System.Threading.Tasks.Task<string> TxProductTypeAsync(string typeNo, string typeName, string typeDesc) {
            return base.Channel.TxProductTypeAsync(typeNo, typeName, typeDesc);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.TransferServiceAMES.TxModelResponse CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxModel(CycleTimeRecord.TransferServiceAMES.TxModelRequest request) {
            return base.Channel.TxModel(request);
        }
        
        public string TxModel(string modelNo, string modelName, string modelSpec, string modelUnit, string modelDesc, string modelGroup, System.Nullable<int> productTypeId, string modelType, System.Nullable<int> burnTime) {
            CycleTimeRecord.TransferServiceAMES.TxModelRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxModelRequest();
            inValue.modelNo = modelNo;
            inValue.modelName = modelName;
            inValue.modelSpec = modelSpec;
            inValue.modelUnit = modelUnit;
            inValue.modelDesc = modelDesc;
            inValue.modelGroup = modelGroup;
            inValue.productTypeId = productTypeId;
            inValue.modelType = modelType;
            inValue.burnTime = burnTime;
            CycleTimeRecord.TransferServiceAMES.TxModelResponse retVal = ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxModel(inValue);
            return retVal.TxModelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxModelResponse> CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxModelAsync(CycleTimeRecord.TransferServiceAMES.TxModelRequest request) {
            return base.Channel.TxModelAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxModelResponse> TxModelAsync(string modelNo, string modelName, string modelSpec, string modelUnit, string modelDesc, string modelGroup, System.Nullable<int> productTypeId, string modelType, System.Nullable<int> burnTime) {
            CycleTimeRecord.TransferServiceAMES.TxModelRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxModelRequest();
            inValue.modelNo = modelNo;
            inValue.modelName = modelName;
            inValue.modelSpec = modelSpec;
            inValue.modelUnit = modelUnit;
            inValue.modelDesc = modelDesc;
            inValue.modelGroup = modelGroup;
            inValue.productTypeId = productTypeId;
            inValue.modelType = modelType;
            inValue.burnTime = burnTime;
            return ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxModelAsync(inValue);
        }
        
        public string TxFlow(string flowName, string flowDesc, string unitNo) {
            return base.Channel.TxFlow(flowName, flowDesc, unitNo);
        }
        
        public System.Threading.Tasks.Task<string> TxFlowAsync(string flowName, string flowDesc, string unitNo) {
            return base.Channel.TxFlowAsync(flowName, flowDesc, unitNo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoResponse CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxWorkOrderInfo(CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoRequest request) {
            return base.Channel.TxWorkOrderInfo(request);
        }
        
        public string TxWorkOrderInfo(string woNo, System.Nullable<int> planQty, string unitNo, System.Nullable<int> productTypeId, string modelNo, System.Nullable<int> woType, string engSr) {
            CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoRequest();
            inValue.woNo = woNo;
            inValue.planQty = planQty;
            inValue.unitNo = unitNo;
            inValue.productTypeId = productTypeId;
            inValue.modelNo = modelNo;
            inValue.woType = woType;
            inValue.engSr = engSr;
            CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoResponse retVal = ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxWorkOrderInfo(inValue);
            return retVal.TxWorkOrderInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoResponse> CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxWorkOrderInfoAsync(CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoRequest request) {
            return base.Channel.TxWorkOrderInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoResponse> TxWorkOrderInfoAsync(string woNo, System.Nullable<int> planQty, string unitNo, System.Nullable<int> productTypeId, string modelNo, System.Nullable<int> woType, string engSr) {
            CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxWorkOrderInfoRequest();
            inValue.woNo = woNo;
            inValue.planQty = planQty;
            inValue.unitNo = unitNo;
            inValue.productTypeId = productTypeId;
            inValue.modelNo = modelNo;
            inValue.woType = woType;
            inValue.engSr = engSr;
            return ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxWorkOrderInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartResponse CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxWorkOrderInsertAndStart(CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartRequest request) {
            return base.Channel.TxWorkOrderInsertAndStart(request);
        }
        
        public string TxWorkOrderInsertAndStart(string woNo, System.Nullable<int> planQty, string unitNo, System.Nullable<int> productTypeId, string modelNo, System.Nullable<int> woType, System.Nullable<int> lineId, System.Nullable<int> flowId, string engSr) {
            CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartRequest();
            inValue.woNo = woNo;
            inValue.planQty = planQty;
            inValue.unitNo = unitNo;
            inValue.productTypeId = productTypeId;
            inValue.modelNo = modelNo;
            inValue.woType = woType;
            inValue.lineId = lineId;
            inValue.flowId = flowId;
            inValue.engSr = engSr;
            CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartResponse retVal = ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxWorkOrderInsertAndStart(inValue);
            return retVal.TxWorkOrderInsertAndStartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartResponse> CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxWorkOrderInsertAndStartAsync(CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartRequest request) {
            return base.Channel.TxWorkOrderInsertAndStartAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartResponse> TxWorkOrderInsertAndStartAsync(string woNo, System.Nullable<int> planQty, string unitNo, System.Nullable<int> productTypeId, string modelNo, System.Nullable<int> woType, System.Nullable<int> lineId, System.Nullable<int> flowId, string engSr) {
            CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxWorkOrderInsertAndStartRequest();
            inValue.woNo = woNo;
            inValue.planQty = planQty;
            inValue.unitNo = unitNo;
            inValue.productTypeId = productTypeId;
            inValue.modelNo = modelNo;
            inValue.woType = woType;
            inValue.lineId = lineId;
            inValue.flowId = flowId;
            inValue.engSr = engSr;
            return ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxWorkOrderInsertAndStartAsync(inValue);
        }
        
        public string PassStation(string barcodeNo, int lineId, string unitNo, int stationId, int woId, int flowId, System.DateTime collectDate, string ruleStatus) {
            return base.Channel.PassStation(barcodeNo, lineId, unitNo, stationId, woId, flowId, collectDate, ruleStatus);
        }
        
        public System.Threading.Tasks.Task<string> PassStationAsync(string barcodeNo, int lineId, string unitNo, int stationId, int woId, int flowId, System.DateTime collectDate, string ruleStatus) {
            return base.Channel.PassStationAsync(barcodeNo, lineId, unitNo, stationId, woId, flowId, collectDate, ruleStatus);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.TransferServiceAMES.TxWorkManpowerResponse CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxWorkManpower(CycleTimeRecord.TransferServiceAMES.TxWorkManpowerRequest request) {
            return base.Channel.TxWorkManpower(request);
        }
        
        public string TxWorkManpower(
                    System.Nullable<int> POWER_ID, 
                    string POWER_DATE, 
                    string USER_NO, 
                    string USER_NAME, 
                    string UNIT_NO, 
                    System.Nullable<int> CLASS_ID, 
                    System.Nullable<double> OVER_H, 
                    System.Nullable<double> PREPAR_REST_H, 
                    System.Nullable<double> FACT_REST_H, 
                    System.Nullable<double> LEAVE_H, 
                    double FACT_WORK_H, 
                    System.Nullable<int> BREAK_TIME, 
                    string CLASS_NO, 
                    string WERKS, 
                    System.Nullable<int> LINE_ID, 
                    System.Nullable<int> STATION_ID) {
            CycleTimeRecord.TransferServiceAMES.TxWorkManpowerRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxWorkManpowerRequest();
            inValue.POWER_ID = POWER_ID;
            inValue.POWER_DATE = POWER_DATE;
            inValue.USER_NO = USER_NO;
            inValue.USER_NAME = USER_NAME;
            inValue.UNIT_NO = UNIT_NO;
            inValue.CLASS_ID = CLASS_ID;
            inValue.OVER_H = OVER_H;
            inValue.PREPAR_REST_H = PREPAR_REST_H;
            inValue.FACT_REST_H = FACT_REST_H;
            inValue.LEAVE_H = LEAVE_H;
            inValue.FACT_WORK_H = FACT_WORK_H;
            inValue.BREAK_TIME = BREAK_TIME;
            inValue.CLASS_NO = CLASS_NO;
            inValue.WERKS = WERKS;
            inValue.LINE_ID = LINE_ID;
            inValue.STATION_ID = STATION_ID;
            CycleTimeRecord.TransferServiceAMES.TxWorkManpowerResponse retVal = ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxWorkManpower(inValue);
            return retVal.TxWorkManpowerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkManpowerResponse> CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxWorkManpowerAsync(CycleTimeRecord.TransferServiceAMES.TxWorkManpowerRequest request) {
            return base.Channel.TxWorkManpowerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxWorkManpowerResponse> TxWorkManpowerAsync(
                    System.Nullable<int> POWER_ID, 
                    string POWER_DATE, 
                    string USER_NO, 
                    string USER_NAME, 
                    string UNIT_NO, 
                    System.Nullable<int> CLASS_ID, 
                    System.Nullable<double> OVER_H, 
                    System.Nullable<double> PREPAR_REST_H, 
                    System.Nullable<double> FACT_REST_H, 
                    System.Nullable<double> LEAVE_H, 
                    double FACT_WORK_H, 
                    System.Nullable<int> BREAK_TIME, 
                    string CLASS_NO, 
                    string WERKS, 
                    System.Nullable<int> LINE_ID, 
                    System.Nullable<int> STATION_ID) {
            CycleTimeRecord.TransferServiceAMES.TxWorkManpowerRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxWorkManpowerRequest();
            inValue.POWER_ID = POWER_ID;
            inValue.POWER_DATE = POWER_DATE;
            inValue.USER_NO = USER_NO;
            inValue.USER_NAME = USER_NAME;
            inValue.UNIT_NO = UNIT_NO;
            inValue.CLASS_ID = CLASS_ID;
            inValue.OVER_H = OVER_H;
            inValue.PREPAR_REST_H = PREPAR_REST_H;
            inValue.FACT_REST_H = FACT_REST_H;
            inValue.LEAVE_H = LEAVE_H;
            inValue.FACT_WORK_H = FACT_WORK_H;
            inValue.BREAK_TIME = BREAK_TIME;
            inValue.CLASS_NO = CLASS_NO;
            inValue.WERKS = WERKS;
            inValue.LINE_ID = LINE_ID;
            inValue.STATION_ID = STATION_ID;
            return ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxWorkManpowerAsync(inValue);
        }
        
        public System.Data.DataSet RvSensorByIp(string deviceIp) {
            return base.Channel.RvSensorByIp(deviceIp);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RvSensorByIpAsync(string deviceIp) {
            return base.Channel.RvSensorByIpAsync(deviceIp);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.TransferServiceAMES.TxSensorLogResponse CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxSensorLog(CycleTimeRecord.TransferServiceAMES.TxSensorLogRequest request) {
            return base.Channel.TxSensorLog(request);
        }
        
        public string TxSensorLog(System.Nullable<int> sensorId, System.Nullable<int> inputValue, string logDatetime) {
            CycleTimeRecord.TransferServiceAMES.TxSensorLogRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxSensorLogRequest();
            inValue.sensorId = sensorId;
            inValue.inputValue = inputValue;
            inValue.logDatetime = logDatetime;
            CycleTimeRecord.TransferServiceAMES.TxSensorLogResponse retVal = ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxSensorLog(inValue);
            return retVal.TxSensorLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxSensorLogResponse> CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxSensorLogAsync(CycleTimeRecord.TransferServiceAMES.TxSensorLogRequest request) {
            return base.Channel.TxSensorLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxSensorLogResponse> TxSensorLogAsync(System.Nullable<int> sensorId, System.Nullable<int> inputValue, string logDatetime) {
            CycleTimeRecord.TransferServiceAMES.TxSensorLogRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxSensorLogRequest();
            inValue.sensorId = sensorId;
            inValue.inputValue = inputValue;
            inValue.logDatetime = logDatetime;
            return ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxSensorLogAsync(inValue);
        }
        
        public System.Data.DataSet RvWoYieldData(string woNo, string engSr, string startDate, string endDate) {
            return base.Channel.RvWoYieldData(woNo, engSr, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RvWoYieldDataAsync(string woNo, string engSr, string startDate, string endDate) {
            return base.Channel.RvWoYieldDataAsync(woNo, engSr, startDate, endDate);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.TransferServiceAMES.TxStandardTimeResponse CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxStandardTime(CycleTimeRecord.TransferServiceAMES.TxStandardTimeRequest request) {
            return base.Channel.TxStandardTime(request);
        }
        
        public string TxStandardTime(string txtype, System.Nullable<int> stdID, string UNIT_NO, System.Nullable<int> LINE_ID, string ITEM_NO, System.Nullable<int> OP_CNT, System.Nullable<double> FIRST_TIME, System.Nullable<double> TOTAL_CT, System.Nullable<double> CT, System.Nullable<double> MACHINE_CNT, string SIDE, System.Nullable<int> STATION_ID, string MEMO, string uID) {
            CycleTimeRecord.TransferServiceAMES.TxStandardTimeRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxStandardTimeRequest();
            inValue.txtype = txtype;
            inValue.stdID = stdID;
            inValue.UNIT_NO = UNIT_NO;
            inValue.LINE_ID = LINE_ID;
            inValue.ITEM_NO = ITEM_NO;
            inValue.OP_CNT = OP_CNT;
            inValue.FIRST_TIME = FIRST_TIME;
            inValue.TOTAL_CT = TOTAL_CT;
            inValue.CT = CT;
            inValue.MACHINE_CNT = MACHINE_CNT;
            inValue.SIDE = SIDE;
            inValue.STATION_ID = STATION_ID;
            inValue.MEMO = MEMO;
            inValue.uID = uID;
            CycleTimeRecord.TransferServiceAMES.TxStandardTimeResponse retVal = ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxStandardTime(inValue);
            return retVal.TxStandardTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxStandardTimeResponse> CycleTimeRecord.TransferServiceAMES.TransferServiceSoap.TxStandardTimeAsync(CycleTimeRecord.TransferServiceAMES.TxStandardTimeRequest request) {
            return base.Channel.TxStandardTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.TransferServiceAMES.TxStandardTimeResponse> TxStandardTimeAsync(string txtype, System.Nullable<int> stdID, string UNIT_NO, System.Nullable<int> LINE_ID, string ITEM_NO, System.Nullable<int> OP_CNT, System.Nullable<double> FIRST_TIME, System.Nullable<double> TOTAL_CT, System.Nullable<double> CT, System.Nullable<double> MACHINE_CNT, string SIDE, System.Nullable<int> STATION_ID, string MEMO, string uID) {
            CycleTimeRecord.TransferServiceAMES.TxStandardTimeRequest inValue = new CycleTimeRecord.TransferServiceAMES.TxStandardTimeRequest();
            inValue.txtype = txtype;
            inValue.stdID = stdID;
            inValue.UNIT_NO = UNIT_NO;
            inValue.LINE_ID = LINE_ID;
            inValue.ITEM_NO = ITEM_NO;
            inValue.OP_CNT = OP_CNT;
            inValue.FIRST_TIME = FIRST_TIME;
            inValue.TOTAL_CT = TOTAL_CT;
            inValue.CT = CT;
            inValue.MACHINE_CNT = MACHINE_CNT;
            inValue.SIDE = SIDE;
            inValue.STATION_ID = STATION_ID;
            inValue.MEMO = MEMO;
            inValue.uID = uID;
            return ((CycleTimeRecord.TransferServiceAMES.TransferServiceSoap)(this)).TxStandardTimeAsync(inValue);
        }
    }
}
