//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycleTimeRecord.ProcessServiceAMES {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcessServiceAMES.ProcessServiceSoap")]
    public interface ProcessServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  woNo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxStationData", ReplyAction="*")]
        CycleTimeRecord.ProcessServiceAMES.TxStationDataResponse TxStationData(CycleTimeRecord.ProcessServiceAMES.TxStationDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxStationData", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.ProcessServiceAMES.TxStationDataResponse> TxStationDataAsync(CycleTimeRecord.ProcessServiceAMES.TxStationDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  tableName 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxStandardID", ReplyAction="*")]
        CycleTimeRecord.ProcessServiceAMES.TxStandardIDResponse TxStandardID(CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxStandardID", ReplyAction="*")]
        System.Threading.Tasks.Task<CycleTimeRecord.ProcessServiceAMES.TxStandardIDResponse> TxStandardIDAsync(CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TxStationDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TxStationData", Namespace="http://tempuri.org/", Order=0)]
        public CycleTimeRecord.ProcessServiceAMES.TxStationDataRequestBody Body;
        
        public TxStationDataRequest() {
        }
        
        public TxStationDataRequest(CycleTimeRecord.ProcessServiceAMES.TxStationDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TxStationDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string woNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stationName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string barcodeNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string opNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string errorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string errorDesc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string errorLocation;
        
        public TxStationDataRequestBody() {
        }
        
        public TxStationDataRequestBody(string woNo, string stationName, string barcodeNo, string opNo, string errorCode, string errorDesc, string errorLocation) {
            this.woNo = woNo;
            this.stationName = stationName;
            this.barcodeNo = barcodeNo;
            this.opNo = opNo;
            this.errorCode = errorCode;
            this.errorDesc = errorDesc;
            this.errorLocation = errorLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TxStationDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TxStationDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public CycleTimeRecord.ProcessServiceAMES.TxStationDataResponseBody Body;
        
        public TxStationDataResponse() {
        }
        
        public TxStationDataResponse(CycleTimeRecord.ProcessServiceAMES.TxStationDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TxStationDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TxStationDataResult;
        
        public TxStationDataResponseBody() {
        }
        
        public TxStationDataResponseBody(string TxStationDataResult) {
            this.TxStationDataResult = TxStationDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TxStandardIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TxStandardID", Namespace="http://tempuri.org/", Order=0)]
        public CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequestBody Body;
        
        public TxStandardIDRequest() {
        }
        
        public TxStandardIDRequest(CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TxStandardIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        public TxStandardIDRequestBody() {
        }
        
        public TxStandardIDRequestBody(string tableName) {
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TxStandardIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TxStandardIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public CycleTimeRecord.ProcessServiceAMES.TxStandardIDResponseBody Body;
        
        public TxStandardIDResponse() {
        }
        
        public TxStandardIDResponse(CycleTimeRecord.ProcessServiceAMES.TxStandardIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TxStandardIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TxStandardIDResult;
        
        public TxStandardIDResponseBody() {
        }
        
        public TxStandardIDResponseBody(int TxStandardIDResult) {
            this.TxStandardIDResult = TxStandardIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcessServiceSoapChannel : CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessServiceSoapClient : System.ServiceModel.ClientBase<CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap>, CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap {
        
        public ProcessServiceSoapClient() {
        }
        
        public ProcessServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.ProcessServiceAMES.TxStationDataResponse CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap.TxStationData(CycleTimeRecord.ProcessServiceAMES.TxStationDataRequest request) {
            return base.Channel.TxStationData(request);
        }
        
        public string TxStationData(string woNo, string stationName, string barcodeNo, string opNo, string errorCode, string errorDesc, string errorLocation) {
            CycleTimeRecord.ProcessServiceAMES.TxStationDataRequest inValue = new CycleTimeRecord.ProcessServiceAMES.TxStationDataRequest();
            inValue.Body = new CycleTimeRecord.ProcessServiceAMES.TxStationDataRequestBody();
            inValue.Body.woNo = woNo;
            inValue.Body.stationName = stationName;
            inValue.Body.barcodeNo = barcodeNo;
            inValue.Body.opNo = opNo;
            inValue.Body.errorCode = errorCode;
            inValue.Body.errorDesc = errorDesc;
            inValue.Body.errorLocation = errorLocation;
            CycleTimeRecord.ProcessServiceAMES.TxStationDataResponse retVal = ((CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap)(this)).TxStationData(inValue);
            return retVal.Body.TxStationDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.ProcessServiceAMES.TxStationDataResponse> CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap.TxStationDataAsync(CycleTimeRecord.ProcessServiceAMES.TxStationDataRequest request) {
            return base.Channel.TxStationDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.ProcessServiceAMES.TxStationDataResponse> TxStationDataAsync(string woNo, string stationName, string barcodeNo, string opNo, string errorCode, string errorDesc, string errorLocation) {
            CycleTimeRecord.ProcessServiceAMES.TxStationDataRequest inValue = new CycleTimeRecord.ProcessServiceAMES.TxStationDataRequest();
            inValue.Body = new CycleTimeRecord.ProcessServiceAMES.TxStationDataRequestBody();
            inValue.Body.woNo = woNo;
            inValue.Body.stationName = stationName;
            inValue.Body.barcodeNo = barcodeNo;
            inValue.Body.opNo = opNo;
            inValue.Body.errorCode = errorCode;
            inValue.Body.errorDesc = errorDesc;
            inValue.Body.errorLocation = errorLocation;
            return ((CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap)(this)).TxStationDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CycleTimeRecord.ProcessServiceAMES.TxStandardIDResponse CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap.TxStandardID(CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequest request) {
            return base.Channel.TxStandardID(request);
        }
        
        public int TxStandardID(string tableName) {
            CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequest inValue = new CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequest();
            inValue.Body = new CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequestBody();
            inValue.Body.tableName = tableName;
            CycleTimeRecord.ProcessServiceAMES.TxStandardIDResponse retVal = ((CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap)(this)).TxStandardID(inValue);
            return retVal.Body.TxStandardIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CycleTimeRecord.ProcessServiceAMES.TxStandardIDResponse> CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap.TxStandardIDAsync(CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequest request) {
            return base.Channel.TxStandardIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CycleTimeRecord.ProcessServiceAMES.TxStandardIDResponse> TxStandardIDAsync(string tableName) {
            CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequest inValue = new CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequest();
            inValue.Body = new CycleTimeRecord.ProcessServiceAMES.TxStandardIDRequestBody();
            inValue.Body.tableName = tableName;
            return ((CycleTimeRecord.ProcessServiceAMES.ProcessServiceSoap)(this)).TxStandardIDAsync(inValue);
        }
    }
}
