//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycleTimeRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LineWork
    {
        public int sno { get; set; }
        public string EngSr { get; set; }
        public string Line { get; set; }
        public string T_B { get; set; }
        public Nullable<int> BoardSum { get; set; }
        public Nullable<double> Text1 { get; set; }
        public Nullable<double> Text2 { get; set; }
        public Nullable<double> Text3 { get; set; }
        public Nullable<decimal> BottleneckHours { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Other { get; set; }
        public string Mark { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> flag { get; set; }
        public string reason { get; set; }
        public Nullable<int> OP_Cnt { get; set; }
        public string MEmark { get; set; }

        /// <summary>
        /// ME確認原因補充
        /// </summary>
        public string MEmarkAdd { get; set; }
    }
}
